# Generated by Django 5.1.4 on 2025-01-12 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_excerpt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='article',
            name='access_level',
            field=models.CharField(choices=[('private', '私密'), ('protected', '密码保护'), ('shared', '受保护的'), ('public', '公开')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='access_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
